# Generated by Django 5.2.8 on 2025-12-04 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0003_blogtopic_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogtopic',
            name='owner',
        ),
    ]
